name:                computor
version:             0.1.0.0
github:              "acarlson99/computor"
license:             BSD3
author:              "acarlson"
# maintainer:          "example@example.com"
copyright:           "2020 acarlson"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            Polynomial solver
category:            Algorithm

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/acarlson99/computor#readme>

dependencies:
- base >= 4.7 && < 5
- regex-posix
- matrix
- megaparsec
- parsec

library:
  source-dirs: src

executables:
  computor-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - computor

tests:
  computor-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - computor
